Fix/mkt 2696 clone adding custom limit parameter for gatsby build
contentstack/gatsby-source-contentstack pull request #206
Opened 2023-10-23 08:07 UTC by Contentstack-AnkitaD

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18CrxcBY4m4XSdXa3HthJev6HRNS0NI6JA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=k_r3l3q)

- Added the support to make limit value {No. of entries to be fetched at a time} configurable.

2023-10-25 10:09 UTC, abhishek305 requested changes
Few points to check
- bump package version(change needed)
- validate there are no missing data with respect to the stack

2023-10-25 10:09 UTC, abhishek305 commented on src/fetch.js
> +  limit = config?.limit || 50,
you dont need to provide 50 here  as its already configured plugin option schema file as default value please verify and add changes

2023-10-25 10:09 UTC, abhishek305 commented on README.md
> +      limit: 50
also mention that default is kept to 50

2023-10-25 13:09 UTC, abhishek305 requested changes

2023-10-25 13:09 UTC, abhishek305 commented on package.json
> +  "version": "5.2.0",
make it to 5.1.1

2023-10-26 12:18 UTC, surajcontentstack approved these changes

2023-10-26 12:42 UTC, Contentstack-AnkitaD commented
> do we have unit testes for this repo? @Contentstack-AnkitaD

No.

2023-10-26 14:07 UTC, Contentstack-AnkitaD commented
Closing this PR as I need more time for testing... Will merge it once testing is completed

2023-10-27 03:00 UTC, merged