Task/add more default typedefs
contentstack/gatsby-source-contentstack pull request #85
Opened 2021-02-25 17:57 UTC by jbertel2

Making sure that contentTypes with no entries have the created_at and created_by fields, which are default fields for entries.

This is required to not break queries against empty stacks / content types without entries

2021-02-26 18:11 UTC, ninadhatkar commented
@jbertel2 thanks for your contribution we will review the pull request and keep you posted.

2021-04-09 12:12 UTC, ninadhatkar approved these changes

2021-04-28 09:07 UTC, jbertel2 commented
@ninadhatkar  Anything blocking this from being merged?

2021-04-29 04:59 UTC, ninadhatkar commented
@jbertel2 We are planning to have this scheduled for next week's sprint where we will go through QA. Will keep you posted.

2021-05-10 04:21 UTC, ninadhatkar commented
@jbertel2 We noticed one issue while doing QA on this pull request. The data type isoDate is incorrect and it is an issue with the existing filed as well i.e. updatedAt. We are going to update this as a Date once we merge it and push the change along with this. Can you update this here?

2021-06-02 06:17 UTC, ninadhatkar requested changes

2021-06-02 06:17 UTC, ninadhatkar commented on src/normalize.js
> +    data_type: 'isodate',
```suggestion
    data_type: 'Date',
```

2021-08-03 05:41 UTC, merged